package src.main.java.audio;

public enum AudioClipType {

    PLAYER_BULLET_FIRED,
    PLAYER_LASER_BLAST_FIRED,
    PLAYER_MISSILE_FIRED,
    PLAYER_BURST_FIRED,


    ENEMY_EMP_FIRED,
    ENEMY_EMP_HIT,

    MEDIUM_EXPLOSION,
    SMALL_EXPLOSION,
    FUEL_EXPLOSION,
    PROJECTILE_EXPLOSION,
    SHIELD,

}
